note: Service Config to load balance traffic across all Pods with the app=nginx label.  Receives on and sends to port 80.  Exposes an externally accessible endpoint.
sample: |
  kind: Service
  apiVersion: v1
  metadata:
    name: service-example
  spec:
    ports:
      - name: http
        port: 80
        targetPort: 80
    selector:
        app: nginx
    type: LoadBalancer
